// =========================================================================
// NagrikSeva AI - Comprehensive Government Schemes Database (Gujarat & India)
// 26 Major Welfare Schemes across Agriculture, Health, Housing, Education,
// Women & Child, Business, Social Security, and Clean Energy.
// =========================================================================

import { Scheme } from "@/types";

export const SCHEMES_DATA: Scheme[] = [
  // ── 1. AGRICULTURE ──
  {
    id: "pm-kisan",
    name: "PM Kisan Samman Nidhi",
    nameGu: "PM કિસાન સન્માન નિધિ (ખેડૂત સહાય)",
    nameHi: "PM किसान सम्मान निधि",
    category: "agriculture",
    description: "Financial support of ₹6,000/year to all farmer families having cultivable land in 3 direct bank installments.",
    benefits: [
      "₹6,000 પ્રતિ વર્ષ (₹2,000 ના ૩ સમાન હપ્તા)",
      "સીધા બેંક ખાતામાં DBT મારફતે જમા",
      "તમામ સીમાંત અને નાના ખેડૂત પરિવારો પાત્ર",
    ],
    eligibility: { occupation: ["farmer"], maxAge: 99, minAge: 18, gender: "all" },
    documents: ["આધાર કાર્ડ (Aadhaar Card)", "બેંક પાસબુક (Bank Passbook)", "જમીન દસ્તાવેજ ૭/૧૨ અને ૮-અ (7/12 & 8A)", "મોબાઈલ નંબર"],
    applicationUrl: "https://pmkisan.gov.in",
    icon: "🌾",
    ministry: "કૃષિ અને ખેડૂત કલ્યાણ મંત્રાલય (Ministry of Agriculture)",
    isActive: true,
  },
  {
    id: "fasal-bima",
    name: "PM Fasal Bima Yojana",
    nameGu: "PM ફસલ વીમા યોજના (પાક વીમો)",
    nameHi: "PM फसल बीमा योजना",
    category: "agriculture",
    description: "Comprehensive financial support and crop insurance protection against non-preventable natural calamities.",
    benefits: [
      "ખરીફ પાક માટે માત્ર ૨% પ્રીમિયમ અને રવી પાક માટે ૧.૫% પ્રીમિયમ",
      "દુષ્કાળ, પૂર કે કમોસમી વરસાદ સામે ૧૦૦% વીમા કવચ",
      "દાવાની રકમ સીધી બેંક ખાતામાં જમા",
    ],
    eligibility: { occupation: ["farmer"], minAge: 18, maxAge: 99, gender: "all" },
    documents: ["આધાર કાર્ડ", "૭/૧૨, ૮-અ જમીન નકલ", "વાવેતર પ્રમાણપત્ર (તલાટી)", "બેંક પાસબુક રદ કરેલ ચેક"],
    applicationUrl: "https://pmfby.gov.in",
    icon: "🌱",
    ministry: "કૃષિ મંત્રાલય અને રાજ્ય સહકાર વિભાગ",
    isActive: true,
  },
  {
    id: "kisan-credit-card",
    name: "Kisan Credit Card (KCC)",
    nameGu: "કિસાન ક્રેડિટ કાર્ડ (KCC સબસિડી લોન)",
    nameHi: "किसान क्रेडिट कार्ड योजना",
    category: "agriculture",
    description: "Concessional credit for agriculture and allied activities with interest subvention up to ₹3 Lakhs.",
    benefits: [
      "₹૩ લાખ સુધી માત્ર ૪% રાહત દરે ખેતી ધિરાણ",
      "કોઈપણ પ્રકારની વધારાની જામીનગીરી વિના સરળ લોન",
      "એટીએમ સાથે કિસાન ક્રેડિટ કાર્ડ સુવિધા",
    ],
    eligibility: { occupation: ["farmer"], minAge: 18, maxAge: 75, gender: "all" },
    documents: ["આધાર કાર્ડ", "૭/૧૨ ૮-અ નકલ", "તાજેતરનો પાસપોર્ટ ફોટો", "પાક વાવેતર વિગત"],
    applicationUrl: "https://agricoop.nic.in",
    icon: "💳",
    ministry: "નાણાં મંત્રાલય અને નાબાર્ડ (NABARD)",
    isActive: true,
  },
  {
    id: "khedut-sat-pagla",
    name: "Sat Pagla Khedut Kalyan Gujarat",
    nameGu: "સાત પગલાં ખેડૂત કલ્યાણ (ગુજરાત સરકાર)",
    nameHi: "सात पगला खेड़ूत कल्याण योजना",
    category: "agriculture",
    description: "Comprehensive Gujarat Government farmer welfare package including cow maintenance subsidy and small godown grant.",
    benefits: [
      "દેશી ગાય આધારિત પ્રાકૃતિક ખેતી માટે ₹૯૦૦ પ્રતિ માસ (વાર્ષિક ₹૧૦,૮૦૦)",
      "ખેતર પર નાના ગોડાઉન બાંધવા ₹૩૦,૦૦૦ સુધી સહાય",
      "સ્માર્ટ હેન્ડ ટૂલ કીટ ખરીદવા માટે ૭૫% સબસિડી",
    ],
    eligibility: { occupation: ["farmer"], state: ["Gujarat"], minAge: 18, maxAge: 99, gender: "all" },
    documents: ["૭/૧૨ અને ૮-અ નકલ", "આધાર કાર્ડ", "ગાય ટેગિંગ આઈડી (દેશી ગાય માટે)", "બેંક એકાઉન્ટ વિગત"],
    applicationUrl: "https://ikhedut.gujarat.gov.in",
    icon: "🚜",
    ministry: "કૃષિ, ખેડૂત કલ્યાણ અને સહકાર વિભાગ, ગુજરાત સરકાર",
    isActive: true,
  },

  // ── 2. HEALTH ──
  {
    id: "ayushman-bharat",
    name: "Ayushman Bharat PM-JAY",
    nameGu: "આયુષ્માન ભારત PM-JAY (MAA કાર્ડ)",
    nameHi: "आयुष्मान भारत PM-JAY",
    category: "health",
    description: "Free cashless healthcare coverage up to ₹5 Lakh (₹10 Lakh in Gujarat) per family per year for secondary and tertiary hospitalization.",
    benefits: [
      "ગુજરાતના પરિવારો માટે વાર્ષિક ₹૧૦ લાખ સુધી કેશલેસ સારવાર",
      "૨,૫૦૦ થી વધુ સરકારી અને ખાનગી હૉસ્પિટલમાં માન્ય",
      "દવાઓ, ઓપરેશન, ટેસ્ટ અને ICU ચાર્જ સંપૂર્ણપણે મફત",
    ],
    eligibility: { incomeLimit: 400000, gender: "all" },
    documents: ["આધાર કાર્ડ (બધા સભ્યોના)", "રેશન કાર્ડ (Ration Card)", "આવકનું પ્રમાણપત્ર", "PM-JAY પત્ર અથવા મા કાર્ડ"],
    applicationUrl: "https://pmjay.gov.in",
    icon: "🏥",
    ministry: "આરોગ્ય અને પરિવાર કલ્યાણ મંત્રાલય",
    isActive: true,
  },
  {
    id: "maa-amrutam-gujarat",
    name: "Mukhyamantri Amrutam (MAA Vatsalya)",
    nameGu: "મુખ્યમંત્રી અમૃતમ (મા વાત્સલ્ય યોજના)",
    nameHi: "मुख्यमंत्री अमृतम वात्सल्य योजना",
    category: "health",
    description: "Tertiary medical treatment coverage for critical illnesses for low-income and middle-class Gujarat families.",
    benefits: [
      "ગંભીર બીમારીઓ (હૃદયરોગ, કેન્સર, કિડની, ન્યુરો) માટે ૧૦૦% મફત સારવાર",
      "મુસાફરી ભથ્થું ₹૩૦૦ પ્રતિ વિઝિટ મળવાપાત્ર",
      "કોઈપણ પ્રીમિયમ ભર્યા વિના સંપૂર્ણ સરકારી ખર્ચે સારવાર",
    ],
    eligibility: { incomeLimit: 400000, state: ["Gujarat"], gender: "all" },
    documents: ["આવકનો દાખલો (મામલતદાર માન્ય)", "રેશન કાર્ડ", "આધાર કાર્ડ", "પરિવારના ફોટોગ્રાફ"],
    applicationUrl: "https://www.magujarat.com",
    icon: "🩺",
    ministry: "આરોગ્ય અને પરિવાર કલ્યાણ વિભાગ, ગુજરાત સરકાર",
    isActive: true,
  },

  // ── 3. HOUSING ──
  {
    id: "pm-awas-gramin",
    name: "PM Awas Yojana Gramin",
    nameGu: "PM આવાસ યોજના ગ્રામીણ (ગામડાંનું પાકું મકાન)",
    nameHi: "PM आवास योजना ग्रामीण",
    category: "housing",
    description: "Financial assistance for construction of pucca house with basic amenities to all houseless households in rural areas.",
    benefits: [
      "સપાટ વિસ્તારોમાં ₹૧,૨૦,૦૦૦ અને ડુંગરાળ વિસ્તારોમાં ₹૧,૩૦,૦૦૦ સહાય",
      "શૌચાલય બનાવવા વધારાના ₹૧૨,૦૦૦ સહાય",
      "મનરેગા અંતર્ગત ૯૦ દિવસની મજૂરી (અંદાજે ₹૨૦,૦૦૦+)",
    ],
    eligibility: { incomeLimit: 300000, gender: "all", occupation: ["rural"] },
    documents: ["આધાર કાર્ડ", "BPL/SECC યાદી ક્રમાંક", "બેંક પાસબુક", "પ્લોટ/જમીન માલિકી આધાર", "હાલના કાચા મકાનનો ફોટો"],
    applicationUrl: "https://pmayg.nic.in",
    icon: "🏠",
    ministry: "ગ્રામીણ વિકાસ મંત્રાલય (Ministry of Rural Development)",
    isActive: true,
  },
  {
    id: "pm-awas-urban",
    name: "PM Awas Yojana Urban",
    nameGu: "PM આવાસ યોજના શહેરી (શહેરનું ઘર)",
    nameHi: "PM आवास योजना शहरी",
    category: "housing",
    description: "Interest subsidy and financial assistance to urban poor and middle class (EWS/LIG/MIG) for purchasing or constructing pucca houses.",
    benefits: [
      "હોમ લોન વ્યાજ પર ₹૨.૬૭ લાખ સુધી વ્યાજ સબસિડી (CLSS)",
      "સ્લમ રિડેવલપમેન્ટ હેઠળ મફત પાકું આવાસ",
      "પોતાના પ્લોટ પર બાંધકામ માટે ₹૧.૫૦ લાખ સરકારી ગ્રાન્ટ",
    ],
    eligibility: { incomeLimit: 600000, gender: "all" },
    documents: ["આધાર કાર્ડ", "પાન કાર્ડ", "આવકનો દાખલો / IT રિટર્ન", "બેંક સ્ટેટમેન્ટ ૬ માસ", "મકાન દસ્તાવેજ"],
    applicationUrl: "https://pmaymis.gov.in",
    icon: "🏢",
    ministry: "હાઉસિંગ અને શહેરી બાબતોનું મંત્રાલય",
    isActive: true,
  },
  {
    id: "deendayal-awas-gujarat",
    name: "Pandit Deendayal Upadhyay Awas Yojana",
    nameGu: "પંડિત દીનદયાળ ઉપાધ્યાય આવાસ યોજના",
    nameHi: "पंडित दीनदयाल उपाध्याय आवास योजना",
    category: "housing",
    description: "Housing assistance for Socially and Educationally Backward Classes (SEBC) and economically weaker citizens in Gujarat.",
    benefits: [
      "પોતાની માલિકીના પ્લોટ પર મકાન બાંધવા માટે ₹૧,૨૦,૦૦૦ ની સીધી સહાય",
      "૩ હપ્તામાં સીધી બેંક ખાતામાં રકમ જમા",
      "ગ્રામ્ય અને શહેરી બંને વિસ્તારના ગરીબ પરિવારો માટે ઉપલબ્ધ",
    ],
    eligibility: { incomeLimit: 150000, state: ["Gujarat"], gender: "all" },
    documents: ["જાતિનો દાખલો (SEBC/OBC/SC)", "આવકનો દાખલો", "પ્લોટ સનદ અથવા ગામ નમૂના નં ૨", "આધાર કાર્ડ"],
    applicationUrl: "https://esamajkalyan.gujarat.gov.in",
    icon: "🏘️",
    ministry: "સામાજિક ન્યાય અને અધિકારિતા વિભાગ, ગુજરાત સરકાર",
    isActive: true,
  },

  // ── 4. WOMEN & CHILD ──
  {
    id: "sukanya-samriddhi",
    name: "Sukanya Samriddhi Yojana",
    nameGu: "સુકન્યા સમૃદ્ધિ યોજના (દીકરી ભવિષ્ય)",
    nameHi: "सुकन्या समृद्धि योजना",
    category: "women",
    description: "High-interest, tax-free small deposit scheme for girl child education and marriage.",
    benefits: [
      "વાર્ષિક ૮.૨% આકર્ષક વ્યાજ દર (સરકારી સ્કીમમાં સૌથી વધુ)",
      "કલમ 80C હેઠળ ૧૦૦% કરમુક્ત વળતર",
      "દીકરી ૧૮ વર્ષની થતાં ઉચ્ચ અભ્યાસ માટે ૫૦% ઉપાડની છૂટ",
    ],
    eligibility: { gender: "female", maxAge: 10, minAge: 0 },
    documents: ["દીકરીનું જન્મ પ્રમાણપત્ર (Birth Certificate)", "માતા/પિતાનું આધાર કાર્ડ અને પાન કાર્ડ", "સરનામાનો પુરાવો", "ફોટોગ્રાફ"],
    applicationUrl: "https://www.indiapost.gov.in",
    icon: "👧",
    ministry: "નાણાં મંત્રાલય અને ટપાલ વિભાગ",
    isActive: true,
  },
  {
    id: "vahli-dikri-gujarat",
    name: "Vahli Dikri Yojana Gujarat",
    nameGu: "વ્હાલી દીકરી યોજના (ગુજરાત સરકાર)",
    nameHi: "व्हाली दीकरी योजना गुजरात",
    category: "women",
    description: "Gujarat Government initiative to improve girl child sex ratio and promote higher education with total aid of ₹1,10,000.",
    benefits: [
      "પહેલા ધોરણમાં પ્રવેશ વખતે ₹૪,૦૦૦ ની સહાય",
      "નવમા ધોરણમાં પ્રવેશ વખતે ₹૬,૦૦૦ ની સહાય",
      "૧૮ વર્ષ પૂર્ણ થતાં ઉચ્ચ અભ્યાસ/લગ્ન માટે ₹૧,૦૦,૦૦૦ ની એકમષ્ટિ સહાય",
    ],
    eligibility: { gender: "female", incomeLimit: 200000, state: ["Gujarat"], minAge: 0, maxAge: 18 },
    documents: ["દીકરીનું જન્મ પ્રમાણપત્ર", "માતા-પિતાનો આવકનો દાખલો", "રેશન કાર્ડ", "માતા-પિતાનું આધાર કાર્ડ", "બેંક પાસબુક"],
    applicationUrl: "https://wcd.gujarat.gov.in",
    icon: "🎀",
    ministry: "મહિલા અને બાળ વિકાસ વિભાગ, ગુજરાત સરકાર",
    isActive: true,
  },
  {
    id: "pm-matru-vandana",
    name: "PM Matru Vandana Yojana",
    nameGu: "પ્રધાનમંત્રી માતૃ વંદના યોજના (PMMVY)",
    nameHi: "प्रधानमंत्री मातृ वंदना योजना",
    category: "women",
    description: "Maternity benefit scheme providing direct cash assistance of ₹5,000 to pregnant women and lactating mothers.",
    benefits: [
      "પ્રથમ બાળકના જન્મ સમયે ₹૫,૦૦૦ ની સીધી રોકડ સહાય",
      "બીજું બાળક દીકરી હોય તો વધારાના ₹૬,૦૦૦ ની સહાય",
      "પોષણ અને રસીકરણ માટે આંગણવાડી કેન્દ્ર મારફતે ઝડપી ચુકવણી",
    ],
    eligibility: { gender: "female", minAge: 19, maxAge: 45 },
    documents: ["માતૃ-બાળ સુરક્ષા કાર્ડ (MCP Card)", "ગર્ભવતી મહિલા અને પતિનું આધાર કાર્ડ", "બેંક એકાઉન્ટ પાસબુક"],
    applicationUrl: "https://pmmvy.wcd.gov.in",
    icon: "🤱",
    ministry: "મહિલા અને બાળ વિકાસ મંત્રાલય",
    isActive: true,
  },
  {
    id: "mmuy-gujarat",
    name: "Mukhyamantri Mahila Utkarsh Yojana",
    nameGu: "મુખ્યમંત્રી મહિલા ઉત્કર્ષ યોજના (MMUY)",
    nameHi: "मुख्यमंत्री महिला उत्कर्ष योजना",
    category: "women",
    description: "Zero percent interest loans up to ₹1,00,000 to Joint Liability and Earning Groups (JLEG) of women in Gujarat.",
    benefits: [
      "મહિલા સ્વ-સહાય જૂથોને ₹૧,૦૦,૦૦૦ સુધીનું ૦% વ્યાજે ધિરાણ",
      "વ્યાજનો સંપૂર્ણ બોજ ગુજરાત સરકાર ભોગવશે",
      "નાના ગૃહ ઉદ્યોગ અને સ્વરોજગાર શરૂ કરવા શ્રેષ્ઠ તક",
    ],
    eligibility: { gender: "female", state: ["Gujarat"], minAge: 18, maxAge: 60 },
    documents: ["મહિલા સભ્યોના આધાર કાર્ડ", "રેશન કાર્ડ", "બેંક ખાતાની વિગત", "જૂથ સંમતિ પત્ર"],
    applicationUrl: "https://wcd.gujarat.gov.in",
    icon: "👭",
    ministry: "શહેરી વિકાસ અને ગ્રામ વિકાસ વિભાગ, ગુજરાત",
    isActive: true,
  },

  // ── 5. BUSINESS & ENTREPRENEURSHIP ──
  {
    id: "mudra-loan",
    name: "PM Mudra Yojana",
    nameGu: "PM મુદ્રા યોજના (ધંધાકીય લોન)",
    nameHi: "PM मुद्रा योजना",
    category: "business",
    description: "Collateral-free micro loans for non-farm, non-corporate small and micro enterprises up to ₹10 Lakhs.",
    benefits: [
      "શિશુ લોન: ₹૫૦,૦૦૦ સુધી (નાના વ્યવસાય માટે)",
      "કિશોર લોન: ₹૫૦,૦૦૦ થી ₹૫ લાખ સુધી",
      "તરુણ લોન: ₹૫ લાખ થી ₹૧૦ લાખ સુધી (કોઈપણ ગેરંટી વિના)",
    ],
    eligibility: { minAge: 18, maxAge: 65, gender: "all" },
    documents: ["આધાર કાર્ડ અને પાન કાર્ડ", "વ્યવસાયનું સરનામું / ગુમાસ્તા ધારો", "૬ મહિનાનું બેંક સ્ટેટમેન્ટ", "પ્રોજેક્ટ રિપોર્ટ"],
    applicationUrl: "https://mudra.org.in",
    icon: "💼",
    ministry: "નાણાકીય સેવાઓ વિભાગ, નાણાં મંત્રાલય",
    isActive: true,
  },
  {
    id: "pm-svanidhi",
    name: "PM SVANidhi Yojana",
    nameGu: "PM સ્વનિધિ યોજના (શેરી ફેરિયા લોન)",
    nameHi: "PM स्वनिधि योजना",
    category: "business",
    description: "Micro-credit facility for street vendors to restart livelihoods with working capital loans starting from ₹10,000.",
    benefits: [
      "પ્રથમ તબક્કે ₹૧૦,૦૦૦ ની કોઈપણ જામીન વગર લોન",
      "સમયસર ચુકવણી પર બીજા તબક્કે ₹૨૦,૦૦૦ અને ત્રીજા તબક્કે ₹૫૦,૦૦૦",
      "૭% વ્યાજ સબસિડી અને ડિજિટલ પેમેન્ટ પર વાર્ષિક ₹૧,૨૦૦ કેશબેક",
    ],
    eligibility: { minAge: 18, maxAge: 70, gender: "all" },
    documents: ["વેન્ડિંગ પ્રમાણપત્ર અથવા ઓળખપત્ર (ULB)", "આધાર કાર્ડ", "બેંક પાસબુક"],
    applicationUrl: "https://pmsvanidhi.mohua.gov.in",
    icon: "🛒",
    ministry: "હાઉસિંગ અને શહેરી ગરીબી નિવારણ મંત્રાલય",
    isActive: true,
  },
  {
    id: "pm-vishwakarma",
    name: "PM Vishwakarma Yojana",
    nameGu: "PM વિશ્વકર્મા યોજના (કારીગર કલ્યાણ)",
    nameHi: "PM विश्वकर्मा योजना",
    category: "business",
    description: "End-to-end holistic support for traditional artisans and craftspeople across 18 trades including training, toolkit, and loans.",
    benefits: [
      "આધુનિક ટૂલકીટ ખરીદવા માટે ₹૧૫,૦૦૦ ની ઈ-વાઉચર ગ્રાન્ટ",
      "તાલીમ દરમિયાન પ્રતિ દિવસ ₹૫૦૦ નું સ્ટાઈપેન્ડ",
      "માત્ર ૫% રાહત દરે ₹૩,૦૦,૦૦૦ સુધી ગેરંટી મુક્ત લોન",
    ],
    eligibility: { minAge: 18, maxAge: 99, gender: "all" },
    documents: ["આધાર કાર્ડ", "મોબાઈલ નંબર", "બેંક પાસબુક", "પરંપરાગત વ્યવસાયનું સ્વ-ઘોષણાપત્ર"],
    applicationUrl: "https://pmvishwakarma.gov.in",
    icon: "🔨",
    ministry: "સૂક્ષ્મ, લઘુ અને મધ્યમ ઉદ્યોગ મંત્રાલય (MSME)",
    isActive: true,
  },

  // ── 6. EDUCATION & YOUTH ──
  {
    id: "mysy-gujarat",
    name: "Mukhyamantri Yuva Swavalamban Yojana",
    nameGu: "MYSY સ્કોલરશિપ ગુજરાત (ઉચ્ચ શિક્ષણ)",
    nameHi: "मुख्यमंत्री युवा स्वावलंबन योजना",
    category: "education",
    description: "Financial assistance for higher education tuition fees, hostel, and book expenses for bright Gujarat students.",
    benefits: [
      "મેડિકલ અને ડેન્ટલ કોર્સ માટે વાર્ષિક ₹૨,૦૦,૦૦૦ સુધી ટ્યુશન સહાય (૫૦%)",
      "એન્જિનિયરિંગ, ફાર્મસી વગેરે માટે ₹૫૦,૦૦૦ સુધી વાર્ષિક સહાય",
      "હોસ્ટેલ ભથ્થું ₹૧,૨૦૦/માસ અને પુસ્તક ખરીદી માટે ₹૧૦,૦૦૦ ગ્રાન્ટ",
    ],
    eligibility: { incomeLimit: 600000, state: ["Gujarat"], minAge: 16, maxAge: 28, gender: "all" },
    documents: ["ધોરણ ૧૦/૧૨ ની ૮૦ ટકાથી વધુ પર્સન્ટાઇલ વાળી માર્કશીટ", "આવકનો દાખલો (₹૬ લાખ સુધી)", "કોલેજ એડમિશન સ્લિપ અને ફી પહોંચ", "આધાર કાર્ડ"],
    applicationUrl: "https://mysy.guj.nic.in",
    icon: "🎓",
    ministry: "શિક્ષણ વિભાગ, ગુજરાત સરકાર",
    isActive: true,
  },
  {
    id: "digital-gujarat-scholarship",
    name: "Digital Gujarat Post-Matric Scholarship",
    nameGu: "ડિજિટલ ગુજરાત પોસ્ટ-મેટ્રિક શિષ્યવૃત્તિ",
    nameHi: "डिजिटल गुजरात पोस्ट-मैट्रिक स्कॉलरशिप",
    category: "education",
    description: "Scholarship and freeship card scheme for SC, ST, SEBC, and EWS students studying after 10th/12th grade.",
    benefits: [
      "૧૦૦% ટ્યુશન ફી માફી અથવા સીધું રિફંડ",
      "વાર્ષિક નિર્વાહ ભથ્થું (Maintenance Allowance) સીધું બેંકમાં",
      "ડિપ્લોમા, ડિગ્રી, માસ્ટર્સ અને પીએચડી તમામ કોર્સ માન્ય",
    ],
    eligibility: { incomeLimit: 250000, state: ["Gujarat"], minAge: 15, maxAge: 35, gender: "all" },
    documents: ["જાતિ પ્રમાણપત્ર (Caste Certificate)", "આવકનો દાખલો", "છેલ્લી પાસ કરેલી પરીક્ષાની માર્કશીટ", "કોલેજ ફી રસીદ અને બોનાફાઇડ"],
    applicationUrl: "https://www.digitalgujarat.gov.in",
    icon: "📚",
    ministry: "સામાજિક ન્યાય અને આદિજાતિ વિકાસ વિભાગ, ગુજરાત",
    isActive: true,
  },
  {
    id: "skill-india",
    name: "PM Kaushal Vikas Yojana",
    nameGu: "PM કૌશલ્ય વિકાસ યોજના (PMKVY 4.0)",
    nameHi: "PM कौशल विकास योजना",
    category: "education",
    description: "Industry-relevant short-term skill training and National Skill Qualification Framework (NSQF) certification.",
    benefits: [
      "સંપૂર્ણપણે મફત કૌશલ્ય તાલીમ (Free Practical Training)",
      "ભારત સરકાર માન્ય કૌશલ્ય પ્રમાણપત્ર",
      "તાલીમ પાસ થતાં ₹૮,૦૦૦ સુધી પ્રોત્સાહક રકમ અને પ્લેસમેન્ટ સહાય",
    ],
    eligibility: { minAge: 15, maxAge: 45, gender: "all" },
    documents: ["આધાર કાર્ડ", "શૈક્ષણિક લાયકાતનું સર્ટિફિકેટ", "બેંક પાસબુક", "પાસપોર્ટ ફોટો"],
    applicationUrl: "https://pmkvyofficial.org",
    icon: "🛠️",
    ministry: "કૌશલ્ય વિકાસ અને ઉદ્યોગસાહસિકતા મંત્રાલય",
    isActive: true,
  },

  // ── 7. SOCIAL SECURITY & PENSION ──
  {
    id: "jan-dhan",
    name: "PM Jan Dhan Yojana",
    nameGu: "PM જન ધન યોજના (ઝીરો બેલેન્સ ખાતું)",
    nameHi: "PM जन धन योजना",
    category: "social",
    description: "Universal banking access with zero minimum balance, RuPay debit card, and in-built accident insurance.",
    benefits: [
      "ઝીરો બેલેન્સ ખાતું (કોઈપણ મિનિમમ બેલેન્સની જરૂર નથી)",
      "₹૨,૦૦,૦૦૦ નું મફત અકસ્માત વીમા કવચ (RuPay Card સાથે)",
      "સંતોષકારક ખાતા સંચાલન પર ₹૧૦,૦૦૦ સુધીની ઓવરડ્રાફ્ટ સુવિધા",
    ],
    eligibility: { minAge: 10, maxAge: 99, gender: "all" },
    documents: ["આધાર કાર્ડ", "૧ પાસપોર્ટ સાઇઝ ફોટો", "મોબાઈલ નંબર"],
    applicationUrl: "https://pmjdy.gov.in",
    icon: "🏦",
    ministry: "નાણાંકીય સેવાઓ વિભાગ, નાણાં મંત્રાલય",
    isActive: true,
  },
  {
    id: "atal-pension",
    name: "Atal Pension Yojana",
    nameGu: "અટલ પેન્શન યોજના (માસિક પેન્શન)",
    nameHi: "अटल पेंशन योजना",
    category: "social",
    description: "Guaranteed minimum monthly pension for unorganized sector citizens after the age of 60.",
    benefits: [
      "૬૦ વર્ષની વય બાદ આજીવન ₹૧,૦૦૦ થી ₹૫,૦૦૦ માસિક પેન્શન",
      "સભ્યના અવસાન બાદ પત્ની/પતિને આજીવન સમાન પેન્શન",
      "દંપતીના અવસાન બાદ નોમિનીને સંપૂર્ણ એકત્રિત ભંડોળ પરત",
    ],
    eligibility: { minAge: 18, maxAge: 40, gender: "all" },
    documents: ["આધાર કાર્ડ", "બચત બેંક ખાતું", "મોબાઈલ નંબર"],
    applicationUrl: "https://npscra.nsdl.co.in",
    icon: "👴",
    ministry: "પેન્શન ફંડ નિયમન અને વિકાસ સત્તામંડળ (PFRDA)",
    isActive: true,
  },
  {
    id: "shram-yogi-maandhan",
    name: "PM Shram Yogi Maandhan",
    nameGu: "PM શ્રમયોગી માનધન યોજના (PMSYM)",
    nameHi: "PM श्रम योगी मानधन योजना",
    category: "social",
    description: "Old age pension protection for unorganized workers like drivers, domestic helpers, tailors, and construction workers.",
    benefits: [
      "૬૦ વર્ષ પછી નિશ્ચિત ₹૩,૦૦૦ પ્રતિ માસ પેન્શન",
      "૫૦% સરકારી સબસિડી (જેટલું પ્રીમિયમ નાગરિક ભરે તેટલું સરકાર ઉમેરે)",
      "ઈ-શ્રમ કાર્ડ ધારકો માટે તાત્કાલિક નોંધણી",
    ],
    eligibility: { incomeLimit: 180000, minAge: 18, maxAge: 40, gender: "all" },
    documents: ["આધાર કાર્ડ", "બચત બેંક પાસબુક (IFSC સાથે)", "મોબાઈલ નંબર"],
    applicationUrl: "https://maandhan.in",
    icon: "👷",
    ministry: "શ્રમ અને રોજગાર મંત્રાલય (Ministry of Labour)",
    isActive: true,
  },
  {
    id: "niradhar-vridh-pension",
    name: "Niradhar Vrudhh Pension Gujarat",
    nameGu: "નિરાધાર વૃદ્ધ પેન્શન સહાય (ગુજરાત)",
    nameHi: "निराधार वृद्ध पेंशन योजना गुजरात",
    category: "social",
    description: "Monthly financial pension to destitute elderly citizens in Gujarat aged 60 and above with no source of income.",
    benefits: [
      "૬૦ થી ૭૯ વર્ષના વૃદ્ધોને ₹૧,૦૦૦ પ્રતિ માસ સીધા ખાતામાં",
      "૮૦ વર્ષથી વધુ ઉંમરના વડીલોને ₹૧,૨૫૦ પ્રતિ માસ",
      "પોસ્ટ ઓફિસ અથવા બેંક મારફતે નિયમિત દર મહિને ચુકવણી",
    ],
    eligibility: { minAge: 60, maxAge: 99, state: ["Gujarat"], incomeLimit: 120000, gender: "all" },
    documents: ["ઉંમરનો પુરાવો (શાળા છોડ્યાનું પ્રમાણપત્ર/ચૂંટણી કાર્ડ)", "આવકનો દાખલો", "કોઈ પુખ્ત દીકરો ન હોવાનું સોગંદનામું", "આધાર કાર્ડ"],
    applicationUrl: "https://esamajkalyan.gujarat.gov.in",
    icon: "🧓",
    ministry: "સામાજિક ન્યાય અને અધિકારિતા વિભાગ, ગુજરાત સરકાર",
    isActive: true,
  },
  {
    id: "annapurna-yojana",
    name: "Shramik Annapurna Yojana",
    nameGu: "શ્રમિક અન્નપૂર્ણા યોજના (માત્ર ₹૫ માં ભોજન)",
    nameHi: "श्रमिक अन्नपूर्णा योजना",
    category: "social",
    description: "Nutritious and hygienic hot cooked meal to construction workers and daily wagers at Kadiyanaka across Gujarat.",
    benefits: [
      "માત્ર ₹૫ માં સંપૂર્ણ પૌષ્ટિક ગરમ ભોજન (રોટલી, શાક, દાળ, ભાત)",
      "ગુજરાતના તમામ મુખ્ય કડિયાનાકા પર વિશેષ ભોજન કેન્દ્રો",
      "શ્રમિક પરિવારજનો માટે પણ રાહત દરે ભોજન સુવિધા",
    ],
    eligibility: { occupation: ["laborer", "construction"], state: ["Gujarat"], gender: "all" },
    documents: ["ઈ-નિર્માણ કાર્ડ (E-Nirman Card)", "આધાર કાર્ડ"],
    applicationUrl: "https://enirmanbocw.gujarat.gov.in",
    icon: "🍲",
    ministry: "શ્રમ, કૌશલ્ય વિકાસ અને રોજગાર વિભાગ, ગુજરાત",
    isActive: true,
  },

  // ── 8. ENERGY & ENVIRONMENT ──
  {
    id: "ujjwala-yojana",
    name: "PM Ujjwala Yojana 2.0",
    nameGu: "PM ઉજ્જવલા યોજના (મફત ગેસ સિલિન્ડર)",
    nameHi: "PM उज्ज्वला योजना",
    category: "energy",
    description: "Free LPG gas connection with zero security deposit and first refill free for women from poor households.",
    benefits: [
      "સંપૂર્ણપણે મફત નવું ગેસ કનેક્શન (સિક્યોરિટી ડિપોઝિટ શૂન્ય)",
      "પ્રથમ ભરેલો સિલિન્ડર અને ચૂલો (Stove) તદ્દન મફત",
      "આગામી દરેક રિફિલ પર સરકાર દ્વારા સીધી સબસિડી",
    ],
    eligibility: { gender: "female", incomeLimit: 200000, minAge: 18, maxAge: 99 },
    documents: ["મહિલા અરજદારનું આધાર કાર્ડ", "BPL/SECC રેશન કાર્ડ", "બેંક પાસબુક", "પાસપોર્ટ ફોટો"],
    applicationUrl: "https://pmuy.gov.in",
    icon: "🔥",
    ministry: "પેટ્રોલિયમ અને કુદરતી ગેસ મંત્રાલય",
    isActive: true,
  },
  {
    id: "pm-surya-ghar",
    name: "PM Surya Ghar: Muft Bijli Yojana",
    nameGu: "PM સૂર્ય ઘર: મફત વીજળી યોજના (સોલાર સબસિડી)",
    nameHi: "PM सूर्य घर: मुफ्त बिजली योजना",
    category: "energy",
    description: "National rooftop solar scheme providing up to 300 units of free electricity every month with upfront central subsidy up to ₹78,000.",
    benefits: [
      "પ્રતિ માસ ૩૦૦ યુનિટ સુધી મફત સૌર વીજળી (શૂન્ય લાઈટ બિલ)",
      "૧ થી ૩ કિલોવોટ રૂફટોપ સોલાર સિસ્ટમ પર ₹૩૦,૦૦૦ થી ₹૭૮,૦૦૦ સીધી સબસિડી",
      "વધારાની ઉત્પન્ન થયેલી વીજળી ગ્રીડને વેચીને વધારાની કમાણી",
    ],
    eligibility: { minAge: 18, maxAge: 99, gender: "all" },
    documents: ["છેલ્લા ૬ મહિનાનું વીજળી બિલ (Electricity Consumer No)", "ઘર માલિકીનો દસ્તાવેજ/વેરા બિલ", "આધાર કાર્ડ", "બેંક રદ કરેલ ચેક"],
    applicationUrl: "https://pmsuryaghar.gov.in",
    icon: "☀️",
    ministry: "નવી અને નવીનીકરણીય ઊર્જા મંત્રાલય (MNRE)",
    isActive: true,
  },
];

// Helper functions for offline fallback & server-side lookup
export function getSchemesByCategory(category: string): Scheme[] {
  return SCHEMES_DATA.filter((s) => s.category === category && s.isActive);
}

export function searchSchemes(query: string): Scheme[] {
  const q = query.toLowerCase();
  return SCHEMES_DATA.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.nameGu.includes(q) ||
      s.description.toLowerCase().includes(q) ||
      s.category.toLowerCase().includes(q) ||
      s.ministry.toLowerCase().includes(q)
  );
}

export function getSchemeById(id: string): Scheme | undefined {
  return SCHEMES_DATA.find((s) => s.id === id);
}

export const CATEGORY_LABELS: Record<string, { label: string; icon: string; color: string; labelGu: string }> = {
  agriculture: { label: "Agriculture", icon: "🌾", color: "green", labelGu: "ખેતીવાડી & પશુપાલન" },
  health: { label: "Health", icon: "🏥", color: "red", labelGu: "આરોગ્ય & સારવાર" },
  housing: { label: "Housing", icon: "🏠", color: "orange", labelGu: "આવાસ & મકાન" },
  education: { label: "Education", icon: "🎓", color: "blue", labelGu: "શિક્ષણ & શિષ્યવૃત્તિ" },
  women: { label: "Women & Child", icon: "👩", color: "pink", labelGu: "મહિલા & બાળ કલ્યાણ" },
  business: { label: "Business & Loans", icon: "💼", color: "purple", labelGu: "રોજગાર & લોન" },
  social: { label: "Social Security", icon: "🤝", color: "teal", labelGu: "સામાજિક સુરક્ષા & પેન્શન" },
  energy: { label: "Clean Energy", icon: "⚡", color: "yellow", labelGu: "વીજળી & સૌર ઊર્જા" },
};
